DOCKER_DESCRIPTION:=UNIX-like reverse engineering framework and command-line toolset
DOCKER_LABELS:= \
		--label org.opencontainers.image.title="radare2" \
		--label org.opencontainers.image.description="$(DOCKER_DESCRIPTION)" \
		--label org.opencontainers.image.ref.name="$(REGISTRY_IMAGE)" \
		--label org.opencontainers.image.version="$(R2_VERSION)" \
		--label org.opencontainers.image.vendor="radareorg" \
		--label org.opencontainers.image.licenses="LGPL-3.0-only" \
		--label org.opencontainers.image.url="https://www.radare.org/" \
		--label org.opencontainers.image.documentation="https://github.com/radareorg/radare2-snap/blob/main/README-containers.md" \
		--label org.opencontainers.image.source="https://github.com/radareorg/radare2-snap" \
		--label org.opencontainers.image.revision="$(R2_SNAP_COMMIT)" \
		--label org.opencontainers.image.base.name="$(BASE_IMAGE)"

DOCKER_ANNOTATIONS_MANIFEST:= \
		--annotation manifest:org.opencontainers.image.title="radare2" \
		--annotation manifest:org.opencontainers.image.description="$(DOCKER_DESCRIPTION)" \
		--annotation manifest:org.opencontainers.image.ref.name="$(REGISTRY_IMAGE)" \
		--annotation manifest:org.opencontainers.image.version="$(R2_VERSION)" \
		--annotation manifest:org.opencontainers.image.vendor="radareorg" \
		--annotation manifest:org.opencontainers.image.licenses="LGPL-3.0-only" \
		--annotation manifest:org.opencontainers.image.url="https://www.radare.org/" \
		--annotation manifest:org.opencontainers.image.documentation="https://github.com/radareorg/radare2-snap/blob/main/README-containers.md" \
		--annotation manifest:org.opencontainers.image.source="https://github.com/radareorg/radare2-snap" \
		--annotation manifest:org.opencontainers.image.revision="$(R2_SNAP_COMMIT)" \
		--annotation manifest:org.opencontainers.image.base.name="$(BASE_IMAGE)"

DOCKER_ANNOTATIONS_INDEX:= \
		--annotation index:org.opencontainers.image.title="radare2" \
		--annotation index:org.opencontainers.image.description="$(DOCKER_DESCRIPTION)" \
		--annotation index:org.opencontainers.image.ref.name="$(REGISTRY_IMAGE)" \
		--annotation index:org.opencontainers.image.version="$(R2_VERSION)" \
		--annotation index:org.opencontainers.image.vendor="radareorg" \
		--annotation index:org.opencontainers.image.licenses="LGPL-3.0-only" \
		--annotation index:org.opencontainers.image.url="https://www.radare.org/" \
		--annotation index:org.opencontainers.image.documentation="https://github.com/radareorg/radare2-snap/blob/main/README-containers.md" \
		--annotation index:org.opencontainers.image.source="https://github.com/radareorg/radare2-snap" \
		--annotation index:org.opencontainers.image.revision="$(R2_SNAP_COMMIT)"
