name: SBOM manual upload
on:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
    inputs:
      platform:
        description: Docker platform
        required: true
        default: linux/amd64
        type: choice
        options: 
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/386
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: write
    steps:     
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Generate SBOM with Syft from latest AMD64 image
        run: syft scan registry:${{ vars.DOCKERHUB_REPO }}:latest --platform ${{ inputs.platform }} --select-catalogers "+sbom-cataloger" --output spdx-json=docker.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v5
        with:
          name: docker-sbom
          path: docker.spdx.json

      - name: Upload SBOM to GitHub dependency submission API
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
